import type {
  Agent,
  AuditEntry,
  Automation,
  AutomationFolder,
  Broadcast,
  BroadcastFolder,
  Connection,
  ConnectionFolder,
  Contact,
  Conversation,
  CustomFieldDef,
  Deal,
  Message,
  MessageTemplate,
  PipelineStage,
  Tag,
  WebhookEvent,
} from "./types";
import { EB_FUNNEL_TAGS } from "./report-seed";
import { SEDES_DEMO } from "./scope";
import { emptyWaba } from "./whatsapp";

/** Tags de operação + funil Escola Bíblica (relatório consolidado) */
export const TAGS: Tag[] = [
  { id: "t1", name: "ativaIA", color: "#12aa29" },
  { id: "t2", name: "Ex Adventistas Quente", color: "#dc4b4b" },
  { id: "t3", name: "Novo Tempo", color: "#0a417c" },
  { id: "t4", name: "Visita Agendada", color: "#d97706" },
  { id: "t5", name: "Estudo Bíblico", color: "#7c3aed" },
  { id: "t6", name: "Resgate", color: "#0891b2" },
  ...EB_FUNNEL_TAGS.map((t) => ({
    id: t.id,
    name: t.name,
    color: t.color,
  })),
];

const CAMPO_OPTIONS = [
  ...SEDES_DEMO.map((s) => s.code),
  "APS",
  "APV",
  "AB",
  "ASPA",
];

export const CUSTOM_FIELDS: CustomFieldDef[] = [
  { id: "cf1", name: "Distrito", type: "text" },
  {
    id: "cf2",
    name: "Variante / Turma",
    type: "select",
    options: ["Manhã", "Tarde", "Noite", "Online"],
  },
  { id: "cf3", name: "Igreja", type: "text" },
  { id: "cf4", name: "Data de interesse", type: "date" },
  {
    id: "cf5",
    name: "Campo / Associação",
    type: "select",
    options: CAMPO_OPTIONS,
  },
  {
    id: "cf6",
    name: "União",
    type: "select",
    options: ["UCB", "UCOB", "ULB", "UNB", "UNEB", "USB", "USEB"],
  },
  {
    id: "cf7",
    name: "Nível do aluno",
    type: "select",
    options: ["Bronze", "Prata", "Ouro", "Diamante"],
  },
  {
    id: "cf8",
    name: "Tipo de visita",
    type: "select",
    options: ["Presencial", "Online", "Não solicitou"],
  },
  // —— Campos extras Escola Bíblica / atendimento ——
  { id: "cf9", name: "E-mail", type: "text" },
  { id: "cf10", name: "Cidade", type: "text" },
  { id: "cf11", name: "Bairro", type: "text" },
  { id: "cf12", name: "Endereço", type: "text" },
  { id: "cf16", name: "Pedido de Oração", type: "text" },
  { id: "cf17", name: "ctwa_id", type: "text" },
  { id: "cf18", name: "ctwa_clid", type: "text" },
  {
    id: "cf13",
    name: "Origem do lead",
    type: "select",
    options: [
      "Anúncio Meta",
      "Instagram",
      "YouTube",
      "Indicação",
      "Igreja",
      "Evento",
      "Site",
      "WhatsApp",
      "Outro",
    ],
  },
  {
    id: "cf14",
    name: "Interesse principal",
    type: "select",
    options: [
      "Visita",
      "Estudo bíblico",
      "Material impresso",
      "Material digital",
      "Grupo de oração",
      "Batismo",
      "Outro",
    ],
  },
  {
    id: "cf15",
    name: "Status EB",
    type: "select",
    options: [
      "Novo",
      "Em contato",
      "Estudando",
      "Visita agendada",
      "Pausa",
      "Concluído",
      "Inativo",
    ],
  },
  {
    id: "cf16",
    name: "Material preferido",
    type: "select",
    options: ["Impresso", "Digital", "Ambos", "Não solicitou"],
  },
  { id: "cf17", name: "Data da visita", type: "date" },
  { id: "cf18", name: "Pastor / responsável", type: "text" },
  {
    id: "cf19",
    name: "Grupo de oração",
    type: "select",
    options: ["Sim", "Não", "Convidado", "Entrou"],
  },
  {
    id: "cf20",
    name: "Preferência de horário",
    type: "select",
    options: ["Manhã", "Tarde", "Noite", "Fim de semana", "Flexível"],
  },
  { id: "cf21", name: "Telefone alternativo", type: "text" },
  { id: "cf22", name: "Observação pastoral", type: "text" },
  { id: "cf23", name: "Igreja de origem", type: "text" },
  { id: "cf24", name: "Data do último contato", type: "date" },
];

const now = Date.now();
const h = (n: number) => new Date(now - n * 3600000).toISOString();
const d = (n: number) => new Date(now - n * 86400000).toISOString();

export const CONTACTS: Contact[] = [
  {
    id: "c1",
    name: "Maria Silva",
    phone: "5591987654321",
    email: "maria.silva@email.com",
    createdAt: d(12),
    tagIds: ["t1", "t3", "eb_estudando", "eb_visita"],
    customFields: {
      cf1: "Belém Centro",
      cf2: "Manhã",
      cf3: "IASD Marco",
      cf5: "ANPA",
      cf6: "UNB",
      cf7: "Bronze",
      cf8: "Presencial",
    },
    connectionId: "cx_anpa",
    notes: [
      {
        id: "n1",
        text: "Aluna da EB — aceitou visita presencial. Encaminhada à ANPA.",
        author: "Ana Costa",
        createdAt: h(5),
      },
    ],
    assignee: "a_anpa1",
    status: "open",
    isDemo: true,
  },
  {
    id: "c2",
    name: "João Pedro Almeida",
    phone: "5511912345678",
    createdAt: d(8),
    tagIds: ["t2", "t6", "eb_nenhum"],
    customFields: {
      cf1: "Zona Leste",
      cf2: "Manhã",
      cf3: "Novo Tempo Tatuapé",
      cf5: "APL",
      cf6: "UCB",
      cf8: "Não solicitou",
    },
    connectionId: "cx_apl",
    notes: [],
    assignee: "a_apl1",
    status: "pending",
    isDemo: true,
  },
  {
    id: "c3",
    name: "Fernanda Rocha",
    phone: "5531988123456",
    email: "fernanda.r@email.com",
    createdAt: d(3),
    tagIds: ["t4", "t5", "eb_estudo", "eb_estudando"],
    customFields: {
      cf1: "Centro BH",
      cf2: "Tarde",
      cf4: "2026-08-01",
      cf5: "AMC",
      cf6: "USEB",
      cf8: "Online",
    },
    connectionId: "cx_amc",
    notes: [
      {
        id: "n2",
        text: "Estudo bíblico online aceito — lição 1 de Apocalipse (AMC).",
        author: "Bruno Lima",
        createdAt: h(20),
      },
    ],
    assignee: "a_amc1",
    status: "open",
    isDemo: true,
  },
  {
    id: "c4",
    name: "Carlos Mendes",
    phone: "5511999887766",
    createdAt: d(20),
    tagIds: ["t3", "eb_nao_loc"],
    customFields: {
      cf1: "Zona Sul SP",
      cf2: "Online",
      cf5: "APL",
      cf6: "UCB",
    },
    connectionId: "cx_apl",
    notes: [],
    status: "resolved",
    isDemo: true,
  },
  {
    id: "c5",
    name: "Patrícia Nunes",
    phone: "5591977001122",
    email: "pat.nunes@email.com",
    createdAt: d(1),
    tagIds: ["t1", "t2", "eb_mkt"],
    customFields: {
      cf1: "Ananindeua",
      cf2: "Noite",
      cf3: "Igreja do Centro",
      cf5: "ANPA",
      cf6: "UNB",
    },
    connectionId: "cx_anpa",
    notes: [
      {
        id: "n3",
        text: "Lead MKT — pediu CD. Já na base regional ANPA.",
        author: "IA Bot",
        createdAt: h(2),
      },
    ],
    assignee: "a_anpa1",
    status: "open",
    isDemo: true,
  },
  {
    id: "c6",
    name: "Ricardo Souza",
    phone: "5591966554433",
    createdAt: d(5),
    tagIds: ["t5", "eb_estudando", "eb_oracao"],
    customFields: {
      cf1: "Castanhal",
      cf2: "Manhã",
      cf5: "ANPA",
      cf6: "UNB",
      cf7: "Bronze",
    },
    connectionId: "cx_anpa",
    notes: [],
    assignee: "a_anpa2",
    status: "open",
    isDemo: true,
  },
  {
    id: "c7",
    name: "Luciana Dias",
    phone: "5511944332211",
    createdAt: d(15),
    tagIds: ["t3", "t4", "eb_visita", "eb_pend"],
    customFields: {
      cf1: "Guarulhos",
      cf2: "Tarde",
      cf5: "APL",
      cf6: "UCB",
      cf8: "Presencial",
    },
    connectionId: "cx_apl",
    notes: [],
    status: "pending",
    isDemo: true,
  },
  {
    id: "c8",
    name: "André Barbosa",
    phone: "5582933221100",
    email: "andre.b@email.com",
    createdAt: d(2),
    tagIds: ["t6", "eb_nao_atend"],
    customFields: {
      cf1: "Maceió",
      cf2: "Noite",
      cf5: "MISAL",
      cf6: "UNEB",
    },
    connectionId: "cx_misal",
    notes: [
      {
        id: "n4",
        text: "Na fila da Missão Alagoas — ainda sem atendente.",
        author: "Sistema",
        createdAt: h(1),
      },
    ],
    status: "open",
    isDemo: true,
  },
  {
    id: "c9",
    name: "Helena Costa",
    phone: "5531977112233",
    createdAt: d(4),
    tagIds: ["eb_estudando", "eb_visita", "t4"],
    customFields: {
      cf1: "Contagem",
      cf2: "Noite",
      cf5: "AMC",
      cf6: "USEB",
      cf8: "Presencial",
    },
    connectionId: "cx_amc",
    notes: [],
    assignee: "a_amc1",
    status: "open",
    isDemo: true,
  },
  {
    id: "c10",
    name: "Paulo Ribeiro",
    phone: "5591999001122",
    createdAt: d(6),
    tagIds: ["eb_estudo", "eb_estudando", "t5"],
    customFields: {
      cf1: "Marituba",
      cf2: "Online",
      cf5: "ANPA",
      cf6: "UNB",
      cf7: "Ouro",
      cf8: "Online",
    },
    connectionId: "cx_anpa",
    notes: [
      {
        id: "n5",
        text: "Estudo online semanal. Nível Ouro no consolidado ANPA.",
        author: "Sede ANPA",
        createdAt: h(12),
      },
    ],
    assignee: "a_anpa2",
    status: "open",
    isDemo: true,
  },
  {
    id: "c11",
    name: "Juliana Freitas",
    phone: "5582944556677",
    createdAt: d(9),
    tagIds: ["eb_mkt", "eb_nenhum"],
    customFields: {
      cf1: "Arapiraca",
      cf2: "Manhã",
      cf5: "MISAL",
      cf6: "UNEB",
    },
    connectionId: "cx_misal",
    notes: [],
    status: "pending",
    isDemo: true,
  },
  {
    id: "c12",
    name: "Marcos Vinícius",
    phone: "5511988776655",
    createdAt: d(7),
    tagIds: ["eb_estudando", "t3"],
    customFields: {
      cf1: "São Miguel",
      cf2: "Tarde",
      cf5: "APL",
      cf6: "UCB",
      cf7: "Prata",
    },
    connectionId: "cx_apl",
    notes: [],
    assignee: "a_apl1",
    status: "open",
    isDemo: true,
  },
];

export const CONVERSATIONS: Conversation[] = [
  {
    id: "cv1",
    contactId: "c1",
    lastMessageAt: h(0.5),
    unread: 2,
    queue: "meus",
    assignee: "a_anpa1",
  },
  {
    id: "cv2",
    contactId: "c2",
    lastMessageAt: h(3),
    unread: 0,
    queue: "ia",
    assignee: "a4",
  },
  {
    id: "cv3",
    contactId: "c3",
    lastMessageAt: h(1),
    unread: 1,
    queue: "meus",
    assignee: "a_amc1",
  },
  {
    id: "cv4",
    contactId: "c5",
    lastMessageAt: h(0.2),
    unread: 3,
    queue: "novos",
  },
  {
    id: "cv5",
    contactId: "c6",
    lastMessageAt: h(8),
    unread: 0,
    queue: "finalizados",
    assignee: "a_anpa2",
  },
  {
    id: "cv6",
    contactId: "c8",
    lastMessageAt: h(0.1),
    unread: 1,
    queue: "novos",
  },
  {
    id: "cv7",
    contactId: "c9",
    lastMessageAt: h(2),
    unread: 0,
    queue: "meus",
    assignee: "a_amc1",
  },
  {
    id: "cv8",
    contactId: "c10",
    lastMessageAt: h(4),
    unread: 1,
    queue: "meus",
    assignee: "a_anpa2",
  },
];

export const MESSAGES: Message[] = [
  {
    id: "m1",
    conversationId: "cv1",
    from: "contact",
    text: "Oi! Vi o anúncio da Escola Bíblica e quero saber mais.",
    createdAt: h(6),
  },
  {
    id: "m2",
    conversationId: "cv1",
    from: "bot",
    text: "Olá, Maria! Bem-vinda à Escola Bíblica Novo Tempo. Você será atendida pela equipe da ANPA.",
    createdAt: h(5.9),
    author: "Bot NT",
  },
  {
    id: "m3",
    conversationId: "cv1",
    from: "contact",
    text: "Sim! Prefiro material impresso se tiver.",
    createdAt: h(5.5),
  },
  {
    id: "m4",
    conversationId: "cv1",
    from: "agent",
    text: "Perfeito. Sou da ANPA — vou agendar a visita presencial. Qual bairro em Belém?",
    createdAt: h(5),
    author: "Lia ANPA",
  },
  {
    id: "m5",
    conversationId: "cv1",
    from: "contact",
    text: "Moro no Marco. Pode ser sábado de manhã?",
    createdAt: h(0.5),
  },
  {
    id: "m6",
    conversationId: "cv2",
    from: "contact",
    text: "Vocês ainda têm aquele estudo sobre o Apocalipse?",
    createdAt: h(4),
  },
  {
    id: "m7",
    conversationId: "cv2",
    from: "bot",
    text: "Sim! Temos o curso de Apocalipse. A APL (SP) fará o acompanhamento.",
    createdAt: h(3.9),
    author: "Bot NT",
  },
  {
    id: "m8",
    conversationId: "cv2",
    from: "contact",
    text: "Quero sim, por favor.",
    createdAt: h(3),
  },
  {
    id: "m9",
    conversationId: "cv3",
    from: "agent",
    text: "Fernanda, confirmando: estudo bíblico online amanhã às 19h (AMC). Tudo certo?",
    createdAt: h(2),
    author: "Diego AMC",
  },
  {
    id: "m10",
    conversationId: "cv3",
    from: "contact",
    text: "Confirmado! Já preparei o caderno.",
    createdAt: h(1),
  },
  {
    id: "m11",
    conversationId: "cv4",
    from: "contact",
    text: "Cheguei pelo Instagram. Quero o material grátis.",
    createdAt: h(0.3),
  },
  {
    id: "m12",
    conversationId: "cv4",
    from: "system",
    text: "Lead MKT → atribuído à base regional ANPA (WhatsApp exclusivo)",
    createdAt: h(0.25),
  },
  {
    id: "m13",
    conversationId: "cv4",
    from: "contact",
    text: "Alguém pode me atender?",
    createdAt: h(0.2),
  },
  {
    id: "m14",
    conversationId: "cv5",
    from: "agent",
    text: "Ricardo, obrigado por participar do grupo de oração na ANPA. Deus abençoe!",
    createdAt: h(10),
    author: "Rafael ANPA",
  },
  {
    id: "m15",
    conversationId: "cv5",
    from: "contact",
    text: "Amém, muito obrigado pelo acompanhamento.",
    createdAt: h(8),
  },
  {
    id: "m16",
    conversationId: "cv6",
    from: "contact",
    text: "Bom dia, quero me inscrever na escola bíblica.",
    createdAt: h(0.1),
  },
  {
    id: "m17",
    conversationId: "cv7",
    from: "contact",
    text: "Aceitei a visita presencial. Vocês vão à Contagem?",
    createdAt: h(3),
  },
  {
    id: "m18",
    conversationId: "cv7",
    from: "agent",
    text: "Sim, Helena! A equipe AMC agenda visitas no ABC mineiro. Sábado às 15h?",
    createdAt: h(2),
    author: "Diego AMC",
  },
  {
    id: "m19",
    conversationId: "cv8",
    from: "contact",
    text: "Terminei a lição 3. Quando é a próxima?",
    createdAt: h(4),
  },
];

export const FOLDERS: AutomationFolder[] = [
  { id: "f1", name: "Captação" },
  { id: "f2", name: "Nutrição" },
  { id: "f3", name: "Visitas e Estudos" },
  { id: "f4", name: "Encaminhamento regional" },
];

export const AUTOMATIONS: Automation[] = [
  {
    id: "au1",
    name: "Boas-vindas Novo Tempo",
    folderId: "f1",
    active: true,
    isDemo: true,
    updatedAt: d(2),
    nodes: [
      {
        id: "n_tr",
        type: "trigger",
        label: "Palavra-chave",
        x: 80,
        y: 160,
        config: { keyword: "oi" },
      },
      {
        id: "n_msg",
        type: "message",
        label: "Mensagem de boas-vindas",
        x: 400,
        y: 140,
        config: {
          text: "Olá! Bem-vindo à Escola Bíblica Novo Tempo",
        },
      },
      {
        id: "n_tag",
        type: "tag",
        label: "Aplicar tag",
        x: 760,
        y: 140,
        config: { tagId: "t3" },
      },
    ],
    edges: [
      { id: "e1", from: "n_tr", to: "n_msg" },
      { id: "e2", from: "n_msg", to: "n_tag" },
    ],
  },
  {
    id: "au2",
    name: "Resgate aluno frio",
    folderId: "f2",
    active: true,
    isDemo: true,
    updatedAt: d(5),
    nodes: [
      {
        id: "n_tr2",
        type: "trigger",
        label: "Tag aplicada",
        x: 60,
        y: 120,
        config: { tagId: "eb_nenhum" },
      },
      {
        id: "n_msg2",
        type: "message",
        label: "Mensagem de resgate",
        x: 300,
        y: 120,
        config: { text: "Sentimos sua falta nos estudos! Quer retomar?" },
      },
    ],
    edges: [{ id: "e3", from: "n_tr2", to: "n_msg2" }],
  },
  {
    id: "au3",
    name: "Encaminhar à sede regional",
    folderId: "f4",
    active: true,
    isDemo: true,
    updatedAt: d(1),
    nodes: [
      {
        id: "n_tr3",
        type: "trigger",
        label: "Visita / Estudo aceito",
        x: 60,
        y: 80,
        config: { tagId: "eb_visita" },
      },
      {
        id: "n_msg3",
        type: "message",
        label: "Aviso ao aluno",
        x: 300,
        y: 80,
        config: {
          text: "Sua sede regional dará continuidade no WhatsApp local.",
        },
      },
      {
        id: "n_tag3",
        type: "tag",
        label: "Marcar na base regional",
        x: 540,
        y: 80,
        config: { tagId: "eb_estudando" },
      },
    ],
    edges: [
      { id: "e4", from: "n_tr3", to: "n_msg3" },
      { id: "e5", from: "n_msg3", to: "n_tag3" },
    ],
  },
];

export const STAGES: PipelineStage[] = [
  { id: "s1", name: "Lead", order: 1 },
  { id: "s2", name: "Aluno", order: 2 },
  { id: "s3", name: "Jornada", order: 3 },
  { id: "s4", name: "Visita", order: 4 },
  { id: "s5", name: "Estudo", order: 5 },
];

export const DEALS: Deal[] = [
  {
    id: "d1",
    contactId: "c1",
    title: "Maria — Visita ANPA",
    stageId: "s4",
    value: 0,
    temperature: 78,
    daysInStage: 3,
    tagIds: ["t3", "t4", "eb_visita"],
  },
  {
    id: "d2",
    contactId: "c2",
    title: "João — Resgate APL",
    stageId: "s3",
    value: 0,
    temperature: 25,
    daysInStage: 8,
    tagIds: ["t2", "t6", "eb_nenhum"],
  },
  {
    id: "d3",
    contactId: "c3",
    title: "Fernanda — Estudo AMC",
    stageId: "s5",
    value: 0,
    temperature: 85,
    daysInStage: 1,
    tagIds: ["t4", "t5", "eb_estudo"],
  },
  {
    id: "d4",
    contactId: "c5",
    title: "Patrícia — Lead MKT ANPA",
    stageId: "s1",
    value: 0,
    temperature: 55,
    daysInStage: 2,
    tagIds: ["t1", "eb_mkt"],
  },
  {
    id: "d5",
    contactId: "c6",
    title: "Ricardo — Oração ANPA",
    stageId: "s5",
    value: 0,
    temperature: 70,
    daysInStage: 14,
    tagIds: ["t5", "eb_oracao"],
  },
  {
    id: "d6",
    contactId: "c7",
    title: "Luciana — Visita APL",
    stageId: "s4",
    value: 0,
    temperature: 40,
    daysInStage: 5,
    tagIds: ["t6", "eb_pend"],
  },
  {
    id: "d7",
    contactId: "c8",
    title: "André — Fila MISAL",
    stageId: "s1",
    value: 0,
    temperature: 30,
    daysInStage: 1,
    tagIds: ["eb_nao_atend"],
  },
  {
    id: "d8",
    contactId: "c9",
    title: "Helena — Visita AMC",
    stageId: "s4",
    value: 0,
    temperature: 72,
    daysInStage: 2,
    tagIds: ["eb_visita"],
  },
  {
    id: "d9",
    contactId: "c10",
    title: "Paulo — Estudo ANPA",
    stageId: "s4",
    value: 0,
    temperature: 90,
    daysInStage: 6,
    tagIds: ["eb_estudo", "eb_estudando"],
  },
];

export const AGENTS: Agent[] = [
  {
    id: "a1",
    name: "Ana Costa",
    email: "ana@escolabiblica.org",
    area: "Central de Relacionamento",
    online: true,
    role: "central",
  },
  {
    id: "a2",
    name: "Bruno Lima",
    email: "bruno@escolabiblica.org",
    area: "Central — Estudos",
    online: true,
    role: "central",
  },
  {
    id: "a3",
    name: "Carla Mendes",
    email: "carla@escolabiblica.org",
    area: "Central — Visitas",
    online: false,
    role: "central",
  },
  {
    id: "a4",
    name: "Bot NT",
    email: "bot@escolabiblica.org",
    area: "InteligêncIA",
    online: true,
    role: "central",
  },
  {
    id: "a_anpa1",
    name: "Lia ANPA",
    email: "lia@anpa.nt",
    area: "Atendimento ANPA",
    online: true,
    role: "regional",
    campoCode: "ANPA",
  },
  {
    id: "a_anpa2",
    name: "Rafael ANPA",
    email: "rafael@anpa.nt",
    area: "Estudos ANPA",
    online: true,
    role: "regional",
    campoCode: "ANPA",
  },
  {
    id: "a_apl1",
    name: "Sofia APL",
    email: "sofia@apl.nt",
    area: "Atendimento APL",
    online: true,
    role: "regional",
    campoCode: "APL",
  },
  {
    id: "a_amc1",
    name: "Diego AMC",
    email: "diego@amc.nt",
    area: "Atendimento AMC",
    online: true,
    role: "regional",
    campoCode: "AMC",
  },
  {
    id: "a_misal1",
    name: "Elisa MISAL",
    email: "elisa@misal.nt",
    area: "Missão Alagoas",
    online: false,
    role: "regional",
    campoCode: "MISAL",
  },
];

function baseWaba(partial?: Partial<ReturnType<typeof emptyWaba>>) {
  return { ...emptyWaba(), demoMode: false, ...partial };
}

export const CONNECTION_FOLDERS: ConnectionFolder[] = [
  { id: "cg_central", name: "Central", status: "enabled", createdAt: "2026-01-10T10:00:00.000Z" },
  { id: "cg_unb", name: "UNB", status: "enabled", createdAt: "2026-01-10T10:00:00.000Z" },
  { id: "cg_ucb", name: "UCB", status: "enabled", createdAt: "2026-01-10T10:00:00.000Z" },
  { id: "cg_useb", name: "USEB", status: "enabled", createdAt: "2026-01-10T10:00:00.000Z" },
  { id: "cg_uneb", name: "UNEB", status: "enabled", createdAt: "2026-01-10T10:00:00.000Z" },
];

const UNIAO_FOLDER: Record<string, string> = {
  UNB: "cg_unb",
  UCB: "cg_ucb",
  USEB: "cg_useb",
  UNEB: "cg_uneb",
};

export const CONNECTIONS: Connection[] = [
  {
    id: "cx_central",
    name: "Test WhatsApp Business Account",
    phone: "+1 555-649-4132",
    handle: "test.waba.nt",
    status: "configurando",
    quality: "Alta",
    limit: "5.000 conversas/dia",
    verified: false,
    scope: "central",
    folderId: "cg_central",
    accountStatus: "Pendente",
    createdAt: "2026-01-12T11:00:00.000Z",
    messages24h: 0,
    conversationsOpen: 0,
    waba: baseWaba({
      appId: "Novo Tempo Pará - Igreja Adventista",
      wabaId: "1360361672915226",
      phoneNumberId: "1148579618349512",
      accessToken: "",
      verifiedName: "Test Number",
      webhookVerifyToken: "chatnt_nt_para_verify",
      demoMode: false,
    }),
  },
  {
    id: "cx_mkt",
    name: "Captação MKT Digital",
    phone: "+55 11 99000-0002",
    handle: "eb.mkt",
    status: "desconectado",
    quality: "Média",
    limit: "1.000 conversas/dia",
    verified: true,
    scope: "central",
    folderId: "cg_central",
    accountStatus: "Aprovado",
    isDemo: true,
    createdAt: "2026-02-01T09:00:00.000Z",
    messages24h: 420,
    conversationsOpen: 31,
    waba: baseWaba({
      phoneNumberId: "100000000000002",
      accessToken: "",
      verifiedName: "EB MKT",
      lastValidatedAt: h(5),
    }),
  },
  ...SEDES_DEMO.map(
    (s, i): Connection => ({
      id: s.connectionId,
      name: `${s.code} · ${s.name}`,
      phone: s.whatsapp,
      handle: s.handle,
      status: i === 0 ? "conectado" : i === 1 ? "configurando" : "desconectado",
      quality: i === 0 ? "Alta" : "Média",
      limit: "500 conversas/dia",
      verified: i === 0,
      scope: "regional",
      campoCode: s.code,
      uniao: s.uniao,
      folderId: UNIAO_FOLDER[s.uniao] ?? "cg_central",
      accountStatus: i === 0 ? "Aprovado" : i === 1 ? "Pendente" : "Pendente",
      isDemo: true,
      createdAt: "2026-03-01T09:00:00.000Z",
      messages24h: i === 0 ? 86 : 0,
      conversationsOpen: i === 0 ? 12 : 0,
      waba: baseWaba({
        phoneNumberId: i === 0 ? `2${10000000000000 + i}` : "",
        accessToken: "",
        verifiedName: i === 0 ? s.name : undefined,
        lastValidatedAt: i === 0 ? h(1) : undefined,
        webhookVerifyToken: `chatnt_${s.code.toLowerCase()}_verify`,
      }),
    }),
  ),
];

export const WEBHOOK_EVENTS: WebhookEvent[] = [
  {
    id: "wh1",
    connectionId: "cx_anpa",
    type: "message_in",
    summary: "Mensagem recebida de Maria Silva",
    payload: '{"from":"5591987654321","type":"text"}',
    createdAt: h(0.5),
    ok: true,
  },
  {
    id: "wh2",
    connectionId: "cx_anpa",
    type: "status",
    summary: "delivered · wamid.xxx",
    payload: '{"status":"delivered"}',
    createdAt: h(0.4),
    ok: true,
  },
  {
    id: "wh3",
    connectionId: "cx_central",
    type: "verify",
    summary: "Webhook verificado pela Meta",
    payload: '{"hub.mode":"subscribe"}',
    createdAt: d(1),
    ok: true,
  },
];

export const AUDIT: AuditEntry[] = [
  {
    id: "au1",
    type: "Encaminhamento",
    status: "OK",
    count: 1,
    data: "Maria Silva → ANPA (visita aceita)",
    author: "Sistema",
    createdAt: h(6),
  },
  {
    id: "au2",
    type: "WABA",
    status: "OK",
    count: 1,
    data: "Token validado · ANPA",
    author: "Lia ANPA",
    createdAt: h(2),
  },
];

export const TEMPLATES: MessageTemplate[] = [
  {
    id: "tpl1",
    name: "Boas-vindas EB",
    category: "Utilidade",
    status: "Aprovado",
    body: "Olá {{nome}}! Bem-vindo(a) à Escola Bíblica Novo Tempo.",
    buttons: ["Quero estudar", "Falar com atendente"],
    language: "pt_BR",
  },
  {
    id: "tpl2",
    name: "Confirmação de visita",
    category: "Utilidade",
    status: "Aprovado",
    body: "{{nome}}, sua visita presencial foi confirmada com a sede {{campo}}.",
    buttons: ["Confirmar", "Reagendar"],
    language: "pt_BR",
  },
  {
    id: "tpl3",
    name: "Convite estudo online",
    category: "Marketing",
    status: "Aprovado",
    body: "Participe do estudo bíblico online com a equipe {{campo}}.",
    buttons: ["Quero participar"],
    language: "pt_BR",
  },
  {
    id: "tpl4",
    name: "Lembrete lição",
    category: "Utilidade",
    status: "Pendente",
    body: "{{nome}}, sua próxima lição está disponível. Responda SIM para continuar.",
    buttons: ["SIM"],
    language: "pt_BR",
  },
];

export const BROADCAST_FOLDERS: BroadcastFolder[] = [
  { id: "bf1", name: "Novo Tempo" },
  { id: "bf2", name: "Mkt Digital" },
  { id: "bf3", name: "Ações Extras" },
];

export const BROADCASTS: Broadcast[] = [
  {
    id: "bc-draft",
    name: "Draft",
    type: "imediato",
    status: "rascunho",
    channel: "whatsapp",
    folderId: "bf1",
    templateId: "tpl3",
    audience: { includeTagIds: [], excludeTagIds: [], tagMode: "any" },
    audienceCount: 0,
    metrics: { sent: 0, delivered: 0, read: 0, failed: 0, clicks: 0 },
    createdAt: d(11),
  },
  {
    id: "bc1",
    name: "Convite Encontro de Amigos Abaetetuba 07/08",
    type: "imediato",
    status: "enviado",
    channel: "whatsapp",
    folderId: "bf1",
    templateId: "tpl3",
    audience: {
      includeTagIds: ["eb_estudando"],
      excludeTagIds: [],
      tagMode: "any",
    },
    audienceCount: 185,
    metrics: {
      sent: 168,
      delivered: 163,
      read: 111,
      failed: 17,
      clicks: 40,
    },
    createdAt: d(38),
    sentAt: d(38),
  },
  {
    id: "bc2",
    name: "Convite Encontro de Amigos Marco 08/08",
    type: "imediato",
    status: "enviado",
    channel: "whatsapp",
    folderId: "bf2",
    templateId: "tpl3",
    audience: { includeTagIds: [], excludeTagIds: [], tagMode: "any" },
    audienceCount: 2060,
    metrics: {
      sent: 1916,
      delivered: 1813,
      read: 1092,
      failed: 144,
      clicks: 210,
    },
    createdAt: d(38),
    sentAt: d(38),
  },
  {
    id: "bc3",
    name: "Convite estudos — ANPA",
    type: "imediato",
    status: "enviado",
    channel: "whatsapp",
    folderId: "bf1",
    templateId: "tpl3",
    audience: {
      includeTagIds: ["eb_estudando"],
      excludeTagIds: [],
      tagMode: "any",
      fieldId: "cf5",
      fieldValue: "ANPA",
    },
    audienceCount: 4,
    metrics: {
      sent: 4,
      delivered: 4,
      read: 3,
      failed: 0,
      clicks: 2,
    },
    createdAt: d(3),
    sentAt: d(3),
  },
];
