/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendentesRouteImport } from './routes/atendentes'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as BroadcastsRouteImport } from './routes/broadcasts'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ERouteImport } from './routes/e'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as IaRouteImport } from './routes/ia'
import { Route as LiveChatRouteImport } from './routes/live-chat'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as SedesRouteImport } from './routes/sedes'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as AutomacoesIdRouteImport } from './routes/automacoes.$id'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendentesRoute = AtendentesRouteImport.update({
  id: '/atendentes',
  path: '/atendentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsRoute = BroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ERoute = ERouteImport.update({
  id: '/e',
  path: '/e',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveChatRoute = LiveChatRouteImport.update({
  id: '/live-chat',
  path: '/live-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const SedesRoute = SedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesIdRoute = AutomacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AutomacoesRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendentes': typeof AtendentesRoute
  '/automacoes': typeof AutomacoesRouteWithChildren
  '/broadcasts': typeof BroadcastsRoute
  '/conexoes': typeof ConexoesRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/e': typeof ERoute
  '/funil': typeof FunilRoute
  '/ia': typeof IaRoute
  '/live-chat': typeof LiveChatRoute
  '/meta': typeof MetaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/painel': typeof PainelRoute
  '/sedes': typeof SedesRoute
  '/treinamentos': typeof TreinamentosRoute
  '/webhooks': typeof WebhooksRoute
  '/automacoes/$id': typeof AutomacoesIdRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendentes': typeof AtendentesRoute
  '/automacoes': typeof AutomacoesRouteWithChildren
  '/broadcasts': typeof BroadcastsRoute
  '/conexoes': typeof ConexoesRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/e': typeof ERoute
  '/funil': typeof FunilRoute
  '/ia': typeof IaRoute
  '/live-chat': typeof LiveChatRoute
  '/meta': typeof MetaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/painel': typeof PainelRoute
  '/sedes': typeof SedesRoute
  '/treinamentos': typeof TreinamentosRoute
  '/webhooks': typeof WebhooksRoute
  '/automacoes/$id': typeof AutomacoesIdRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendentes': typeof AtendentesRoute
  '/automacoes': typeof AutomacoesRouteWithChildren
  '/broadcasts': typeof BroadcastsRoute
  '/conexoes': typeof ConexoesRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/e': typeof ERoute
  '/funil': typeof FunilRoute
  '/ia': typeof IaRoute
  '/live-chat': typeof LiveChatRoute
  '/meta': typeof MetaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/painel': typeof PainelRoute
  '/sedes': typeof SedesRoute
  '/treinamentos': typeof TreinamentosRoute
  '/webhooks': typeof WebhooksRoute
  '/automacoes/$id': typeof AutomacoesIdRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendentes'
    | '/automacoes'
    | '/broadcasts'
    | '/conexoes'
    | '/contatos'
    | '/crm'
    | '/e'
    | '/funil'
    | '/ia'
    | '/live-chat'
    | '/meta'
    | '/monitoramento'
    | '/painel'
    | '/sedes'
    | '/treinamentos'
    | '/webhooks'
    | '/automacoes/$id'
    | '/api/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendentes'
    | '/automacoes'
    | '/broadcasts'
    | '/conexoes'
    | '/contatos'
    | '/crm'
    | '/e'
    | '/funil'
    | '/ia'
    | '/live-chat'
    | '/meta'
    | '/monitoramento'
    | '/painel'
    | '/sedes'
    | '/treinamentos'
    | '/webhooks'
    | '/automacoes/$id'
    | '/api/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/atendentes'
    | '/automacoes'
    | '/broadcasts'
    | '/conexoes'
    | '/contatos'
    | '/crm'
    | '/e'
    | '/funil'
    | '/ia'
    | '/live-chat'
    | '/meta'
    | '/monitoramento'
    | '/painel'
    | '/sedes'
    | '/treinamentos'
    | '/webhooks'
    | '/automacoes/$id'
    | '/api/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendentesRoute: typeof AtendentesRoute
  AutomacoesRoute: typeof AutomacoesRouteWithChildren
  BroadcastsRoute: typeof BroadcastsRoute
  ConexoesRoute: typeof ConexoesRoute
  ContatosRoute: typeof ContatosRoute
  CrmRoute: typeof CrmRoute
  ERoute: typeof ERoute
  FunilRoute: typeof FunilRoute
  IaRoute: typeof IaRoute
  LiveChatRoute: typeof LiveChatRoute
  MetaRoute: typeof MetaRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  PainelRoute: typeof PainelRoute
  SedesRoute: typeof SedesRoute
  TreinamentosRoute: typeof TreinamentosRoute
  WebhooksRoute: typeof WebhooksRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendentes': {
      id: '/atendentes'
      path: '/atendentes'
      fullPath: '/atendentes'
      preLoaderRoute: typeof AtendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts': {
      id: '/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof BroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e': {
      id: '/e'
      path: '/e'
      fullPath: '/e'
      preLoaderRoute: typeof ERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-chat': {
      id: '/live-chat'
      path: '/live-chat'
      fullPath: '/live-chat'
      preLoaderRoute: typeof LiveChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedes': {
      id: '/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes/$id': {
      id: '/automacoes/$id'
      path: '/$id'
      fullPath: '/automacoes/$id'
      preLoaderRoute: typeof AutomacoesIdRouteImport
      parentRoute: typeof AutomacoesRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutomacoesRouteChildren {
  AutomacoesIdRoute: typeof AutomacoesIdRoute
}

const AutomacoesRouteChildren: AutomacoesRouteChildren = {
  AutomacoesIdRoute: AutomacoesIdRoute,
}

const AutomacoesRouteWithChildren = AutomacoesRoute._addFileChildren(
  AutomacoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendentesRoute: AtendentesRoute,
  AutomacoesRoute: AutomacoesRouteWithChildren,
  BroadcastsRoute: BroadcastsRoute,
  ConexoesRoute: ConexoesRoute,
  ContatosRoute: ContatosRoute,
  CrmRoute: CrmRoute,
  ERoute: ERoute,
  FunilRoute: FunilRoute,
  IaRoute: IaRoute,
  LiveChatRoute: LiveChatRoute,
  MetaRoute: MetaRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  PainelRoute: PainelRoute,
  SedesRoute: SedesRoute,
  TreinamentosRoute: TreinamentosRoute,
  WebhooksRoute: WebhooksRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
